BEGIN TRANSACTION;
CREATE TABLE animal (animal_id INTEGER PRIMARY KEY, name TEXT, model_dir TEXT, model_file TEXT, animation TEXT, scale NUMERIC);
INSERT INTO animal VALUES(1,'aardvark','aardvark','aardvark','attack,die,eat,walk',5);
INSERT INTO animal VALUES(2,'africanclawlessotter','africanClawlessOtter','africanClawlessOtter','attack,die,eat,walk',5);
INSERT INTO animal VALUES(3,'africanfisheagle','africanFishEagle','africanFishEagle','attack,die,eat,walk',5);
INSERT INTO animal VALUES(4,'batearedfox','batEaredFox','batEaredFox','attack,die,eat,walk',7);
INSERT INTO animal VALUES(5,'blackbackedjackal','blackBackedJackal','blackBackedJackal','attack,die,eat,walk',7);
INSERT INTO animal VALUES(6,'blackmamba','blackMamba','blackMamba','attack,die,eat,walk',5);
INSERT INTO animal VALUES(7,'buffalo','buffalo','buffalo','attack,die,eat,walk',15);
INSERT INTO animal VALUES(8,'bushbaby','bushBaby','bushBaby','attack,die,eat,walk',5);
INSERT INTO animal VALUES(9,'bushhyrax','bushHyrax','bushHyrax','attack,die,eat,walk',5);
INSERT INTO animal VALUES(10,'bushpig','bushPig','bushPig','attack,die,eat,walk',5);
INSERT INTO animal VALUES(11,'caracal','caracal','caracal','attack,die,eat,walk',15);
INSERT INTO animal VALUES(12,'centipede','centipede','centipede','attack,die,eat,walk',1);
INSERT INTO animal VALUES(13,'cheetah','cheetah','cheetah','attack,die,eat,walk',15);
INSERT INTO animal VALUES(14,'cockroaches','cockroaches','cockroaches','swarm',5);
INSERT INTO animal VALUES(15,'crab','crab','crab','attack,die,eat,walk',5);
INSERT INTO animal VALUES(16,'crocodile','crocodile','crocodile','attack,die,eat,walk',10);
INSERT INTO animal VALUES(17,'dikdik','dikdik','dikdik','attack,die,eat,walk',10);
INSERT INTO animal VALUES(18,'dwarfmongoose','dwarfMongoose','dwarfMongoose','attack,die,eat,walk',5);
INSERT INTO animal VALUES(19,'dwarfsandsnake','dwarfSandSnake','dwarfSandSnake','attack,die,eat,walk',5);
INSERT INTO animal VALUES(20,'eland','eland','eland','attack,die,eat,walk',10);
INSERT INTO animal VALUES(21,'elephant','elephant','elephant','die,eat,walk',7);
INSERT INTO animal VALUES(22,'flies','flies','flies','swarm',5);
INSERT INTO animal VALUES(23,'frog','frog','frog','attack,die,eat,walk',5);
INSERT INTO animal VALUES(24,'gecko','gecko','gecko','attack,die,eat,walk',5);
INSERT INTO animal VALUES(25,'giraffe','giraffe','giraffe','die,eat,walk',10);
INSERT INTO animal VALUES(26,'hare','hare','hare','attack,die,eat,walk',5);
INSERT INTO animal VALUES(27,'hedgehog','hedgehog','hedgehog','attack,die,eat,walk',5);
INSERT INTO animal VALUES(28,'hyena','hyena','hyena','attack,die,eat,walk',5);
INSERT INTO animal VALUES(29,'katydids','katydids','katydids','swarm',5);
INSERT INTO animal VALUES(30,'koriBustard','koriBustard','koriBustard','attack,die,eat,walk',5);
INSERT INTO animal VALUES(31,'leopard','leopard','leopard','attack,die,eat,walk',10);
INSERT INTO animal VALUES(32,'leopardtortoise','leopardTortoise','leopardTortoise','attack,die,eat,walk',5);
INSERT INTO animal VALUES(33,'lion','lion','lion','attack,die,eat,walk',15);
INSERT INTO animal VALUES(34,'mantis','mantis','mantis','attack,die,eat,walk',1);
INSERT INTO animal VALUES(35,'marshowl','marshOwl','marshOwl','attack,die,eat,walk',5);
INSERT INTO animal VALUES(36,'monitorlizard','monitorLizard','monitorLizard','attack,die,eat,walk',5);
INSERT INTO animal VALUES(37,'monkey','monkey','monkey','attack,die,eat,walk',5);
INSERT INTO animal VALUES(38,'ostrich','ostrich','ostrich','attack,die,eat,walk',5);
INSERT INTO animal VALUES(39,'otter','otter','otter','attack,die,eat,walk',5);
INSERT INTO animal VALUES(40,'owlet','owlet','owlet','attack,die,eat,walk',5);
INSERT INTO animal VALUES(41,'pangolin','pangolin','pangolin','attack,die,eat,walk',5);
INSERT INTO animal VALUES(42,'pipistrelle','pipistrelle','pipistrelle','attack,die,eat,walk',5);
INSERT INTO animal VALUES(43,'porcupine','porcupine','porcupine','attack,die,eat,walk',5);
INSERT INTO animal VALUES(44,'ralph','ralph','ralph','run,walk',1);
INSERT INTO animal VALUES(45,'rhino','rhino','rhino','attack,die,eat,walk',15);
INSERT INTO animal VALUES(46,'rufousbeakedsnake','rufousBeakedSnake','rufousBeakedSnake','attack,die,eat,walk',5);
INSERT INTO animal VALUES(47,'scorpion','scorpion','scorpion','attack,die,eat,walk',5);
INSERT INTO animal VALUES(48,'servalcat','servalCat','servalCat','attack,die,eat,walk',5);
INSERT INTO animal VALUES(49,'shrew','shrew','shrew','attack,die,eat,walk',5);
INSERT INTO animal VALUES(50,'sparrow','sparrow','sparrow','die,eat,flap,walk',5);
INSERT INTO animal VALUES(51,'termites','termites','termites','swarm',2);
INSERT INTO animal VALUES(52,'topi','topi','topi','attack,die,eat,walk',10);
INSERT INTO animal VALUES(53,'treemouse','treeMouse','treeMouse','attack,die,eat,walk',5);
INSERT INTO animal VALUES(54,'vulture','vulture','vulture','die,eat,flap,walk',5);
INSERT INTO animal VALUES(55,'whitebelliedbustard','whiteBelliedBustard','whiteBelliedBustard','attack,die,eat,walk',5);
INSERT INTO animal VALUES(56,'wilddog','wildDog','wildDog','attack,die,eat,walk',5);
INSERT INTO animal VALUES(57,'wildebeest','wildebeest','wildebeest','die,eat,walk',5);
INSERT INTO animal VALUES(58,'zebra','zebra','zebra','die,eat,walk',5);
INSERT INTO animal VALUES(59,'thrips','flies','flies','swarm',1);
INSERT INTO animal VALUES(60,'roveandgroundbeetles','flies','flies','swarm',1);
INSERT INTO animal VALUES(61,'orbweaverspider','flies','flies','swarm',1);
INSERT INTO animal VALUES(62,'ants','anthill','anthill','anthill',1);
INSERT INTO animal VALUES(63,'crickets','flies','flies','swarm',1);
INSERT INTO animal VALUES(64,'herbivoroustruebugs','flies','flies','swarm',1);
INSERT INTO animal VALUES(65,'millipedes','centipede','centipede','attack,die,eat,walk',1);
INSERT INTO animal VALUES(66,'grayflycatcher','sparrow','sparrow','die,eat,flap,walk',3);
INSERT INTO animal VALUES(67,'yellowbreastedapalis','sparrow','sparrow','die,eat,flap,walk',3);
INSERT INTO animal VALUES(68,'yellowbelliederemomela','sparrow','sparrow','die,eat,flap,walk',3);
INSERT INTO animal VALUES(69,'redfacedcrombec','sparrow','sparrow','die,eat,flap,walk',3);
INSERT INTO animal VALUES(70,'threebandedplover','sparrow','sparrow','die,eat,flap,walk',3);
INSERT INTO animal VALUES(71,'dwarfepaulettedbat','pipistrelle','pipistrelle','attack,die,eat,walk',3);
INSERT INTO animal VALUES(72,'capeteal','sparrow','sparrow','die,eat,flap,walk',3);
INSERT INTO animal VALUES(73,'creekrat','treeMouse','treeMouse','attack,die,eat,walk',5);
INSERT INTO animal VALUES(74,'catfish','monitorLizard','monitorLizard','attack,die,eat,walk',5);
INSERT INTO animal VALUES(75,'pearlspottedowlet','sparrow','sparrow','die,eat,flap,walk',3);
INSERT INTO animal VALUES(76,'yellowthroatedsandgrouse','sparrow','sparrow','die,eat,flap,walk',3);
INSERT INTO animal VALUES(77,'africangreyhornbill','sparrow','sparrow','die,eat,flap,walk',5);
INSERT INTO animal VALUES(78,'coquifrancolin','sparrow','sparrow','die,eat,flap,walk',3);
INSERT INTO animal VALUES(79,'stripedweasel','shrew','shrew','attack,die,eat,walk',5);
INSERT INTO animal VALUES(80,'hippopotamus','rhino','rhino','attack,die,eat,walk',15);
INSERT INTO animal VALUES(81,'oribi','dikdik','dikdik','attack,die,eat,walk',5);
INSERT INTO animal VALUES(82,'bohorredbuck','dikdik','dikdik','attack,die,eat,walk',5);
INSERT INTO animal VALUES(83,'decayingMaterial','decayingMaterial','decayingMaterial','',1);
INSERT INTO animal VALUES(85,'maraboustark','africanFishEagle','africanFishEagle','attack,die,eat,walk',5);
INSERT INTO animal VALUES(86,'southerngroundhornbill','africanFishEagle','africanFishEagle','attack,die,eat,walk',5);
INSERT INTO animal VALUES(88,'crocodile','crocodile','crocodile','attack,die,eat,walk',5);
INSERT INTO animal VALUES(999,'dummy','dummy','dummy','',5);
CREATE TABLE geo_obj (geo_obj_id INTEGER PRIMARY KEY, name TEXT, model_dir TEXT, model_file TEXT, animation TEXT, scale NUMERIC);
INSERT INTO geo_obj VALUES(1,'anthill','anthill','anthill','',7);
CREATE TABLE map (map_id INTEGER PRIMARY KEY, map_name TEXT, map_bgm TEXT);
INSERT INTO map VALUES(1,'The Table','02.ogg');
CREATE TABLE map_type (map_type_id INTEGER PRIMARY KEY, name TEXT, model_file TEXT);
CREATE TABLE msg (msg_id INTEGER PRIMARY KEY, msg_text TEXT);
INSERT INTO msg VALUES(1,'You have received %s [ %d ]');
INSERT INTO msg VALUES(2,'You have received %d Bytes');
INSERT INTO msg VALUES(3,'You have used %s [ %d ]');
INSERT INTO msg VALUES(4,'Not implemented');
INSERT INTO msg VALUES(5,'You cannot whisper to yourself');
INSERT INTO msg VALUES(6,'You have equipped %s [ %d ]');
INSERT INTO msg VALUES(7,'You have unequipped %s [ %d ]');
INSERT INTO msg VALUES(8,'You have removed %s [ %d ]');
INSERT INTO msg VALUES(9,'%s has been added to your friends list');
INSERT INTO msg VALUES(10,'%s has rejected your friend invite');
INSERT INTO msg VALUES(11,'%s has been removed from your friends list');
INSERT INTO msg VALUES(12,'%s is not on your friends list');
INSERT INTO msg VALUES(13,'%s is offline');
INSERT INTO msg VALUES(14,'%s is unavailable');
INSERT INTO msg VALUES(15,'Sent %s a friend invite');
INSERT INTO msg VALUES(16,'Your inventory is full');
INSERT INTO msg VALUES(17,'You do not meet the level requirement');
INSERT INTO msg VALUES(18,'No description');
INSERT INTO msg VALUES(19,'Sent %s a party invite');
INSERT INTO msg VALUES(20,'Party name, %s,  is unavailable');
INSERT INTO msg VALUES(21,'%s is already in a party');
INSERT INTO msg VALUES(22,'You are not the party leader');
INSERT INTO msg VALUES(23,'%s has rejected your party invite');
INSERT INTO msg VALUES(24,'%s has joined the party');
INSERT INTO msg VALUES(25,'%s has left the party');
INSERT INTO msg VALUES(26,'You have left the party');
INSERT INTO msg VALUES(27,'%s has become the new party leader');
INSERT INTO msg VALUES(28,'Party has been disbanded');
INSERT INTO msg VALUES(29,'Party is full');
INSERT INTO msg VALUES(30,'You are not in a party');
INSERT INTO msg VALUES(31,'Party member must be online');
INSERT INTO msg VALUES(32,'%s has entered the game');
INSERT INTO msg VALUES(33,'%s has left the game');
INSERT INTO msg VALUES(34,'You have become the party leader');
INSERT INTO msg VALUES(35,'You do not meet the requirements');
INSERT INTO msg VALUES(36,'You have eliminated one of the choices');
INSERT INTO msg VALUES(37,'%s has eliminated one of the choices');
INSERT INTO msg VALUES(38,'You have successfully answered the question');
INSERT INTO msg VALUES(39,'You have failed to answer the question. Please try again...');
INSERT INTO msg VALUES(40,'%s has failed to answer the question');
INSERT INTO msg VALUES(41,'%s has successfully answered the question');
INSERT INTO msg VALUES(42,'You have failed to use the item');
INSERT INTO msg VALUES(43,'You''ve been disconnected');
INSERT INTO msg VALUES(44,'You''ve been disconnected by a user from another location');
INSERT INTO msg VALUES(45,'Could not connect to server. Please try again later.');
INSERT INTO msg VALUES(46,'You are dead!');
INSERT INTO msg VALUES(47,'Username is not available');
INSERT INTO msg VALUES(48,'Character name is not available');
INSERT INTO msg VALUES(49,'Registration Complete!');
INSERT INTO msg VALUES(50,'First Name Required');
INSERT INTO msg VALUES(51,'Last Name Required');
INSERT INTO msg VALUES(52,'Student ID Required');
INSERT INTO msg VALUES(53,'Student ID has to be of length 9');
INSERT INTO msg VALUES(54,'Student ID has to be a number');
INSERT INTO msg VALUES(55,'Username Required');
INSERT INTO msg VALUES(56,'Username must not contain spaces');
INSERT INTO msg VALUES(57,'Password Required');
INSERT INTO msg VALUES(58,'Passwords do not match');
INSERT INTO msg VALUES(59,'E-Mail Required');
INSERT INTO msg VALUES(60,'Invalid E-Mail');
INSERT INTO msg VALUES(61,'Character Name Required');
INSERT INTO msg VALUES(62,'Character Name must not contain spaces');
INSERT INTO msg VALUES(63,'Do you want to join %s''s party?');
INSERT INTO msg VALUES(64,'Do you want to be %s''s friend?');
INSERT INTO msg VALUES(65,'Friend already exists');
INSERT INTO msg VALUES(66,'You cannot add yourself');
INSERT INTO msg VALUES(67,'Can not use white spaces');
INSERT INTO msg VALUES(68,'Login Failed!');
INSERT INTO msg VALUES(69,'The account is being used. To continue, you need to log in again.');
INSERT INTO msg VALUES(70,'Getting Ready...');
INSERT INTO msg VALUES(71,'Game Start!');
INSERT INTO msg VALUES(72,'%s''s turn');
INSERT INTO msg VALUES(73,'%s has run out of time!');
INSERT INTO msg VALUES(74,'You''ve run out of time!');
INSERT INTO msg VALUES(75,'You have failed to answer the question');
INSERT INTO msg VALUES(76,'%s is the winner! Try harder next time!');
INSERT INTO msg VALUES(77,'You are the winner!');
INSERT INTO msg VALUES(78,'%s has rolled %d');
INSERT INTO msg VALUES(79,'You''ve rolled %d');
INSERT INTO msg VALUES(80,'Your turn');
INSERT INTO msg VALUES(81,'Your client needs to be updated to run this game.');
INSERT INTO msg VALUES(82,'You''ve gained %s experience points');
INSERT INTO msg VALUES(83,'%s is ready');
INSERT INTO msg VALUES(84,'Dice has rolled %d');
INSERT INTO msg VALUES(85,'Leaving in...');
INSERT INTO msg VALUES(86,'Starting in...');
INSERT INTO msg VALUES(87,'You''ve just leveled up to %d!');
INSERT INTO msg VALUES(88,'Sent %s a trade request');
INSERT INTO msg VALUES(89,'%s has rejected your trade request');
INSERT INTO msg VALUES(90,'%s has accepted your trade request');
INSERT INTO msg VALUES(91,'%s is busy');
INSERT INTO msg VALUES(92,'%s has canceled trade');
INSERT INTO msg VALUES(93,'Trade Complete!');
INSERT INTO msg VALUES(94,'%s has canceled trade request');
INSERT INTO msg VALUES(95,'You are already trading with %s');
INSERT INTO msg VALUES(96,'Do you accept %s''s trade request?');
INSERT INTO msg VALUES(97,'You have accepted %s''s trade request');
INSERT INTO msg VALUES(98,'You have rejected %s''s trade request');
INSERT INTO msg VALUES(99,'You have canceled trade');
INSERT INTO msg VALUES(100,'You have confirmed trade');
INSERT INTO msg VALUES(101,'%s has confirmed trade');
INSERT INTO msg VALUES(102,'Trade Failed!');
INSERT INTO msg VALUES(103,'%s does not have enough space');
INSERT INTO msg VALUES(104,'You do not have enough space');
INSERT INTO msg VALUES(105,'Your feedback is greatly appreciated!');
INSERT INTO msg VALUES(106,'Feedback Received');
INSERT INTO msg VALUES(107,'Feedback Failed');
INSERT INTO msg VALUES(108,'Received %d Bytes');
INSERT INTO msg VALUES(109,'Received %d Experience');
INSERT INTO msg VALUES(110,'Received %s [ %d ]');
INSERT INTO msg VALUES(111,'Subject Required');
INSERT INTO msg VALUES(112,'Message Required');
INSERT INTO msg VALUES(113,'Rating Required');
INSERT INTO msg VALUES(114,'Thanks for your purchase!');
INSERT INTO msg VALUES(115,'You do not have enough Bytes');
INSERT INTO msg VALUES(116,'You have recovered %d health');
INSERT INTO msg VALUES(117,'You have lost %d health');
INSERT INTO msg VALUES(118,'Sent %s a duel request');
INSERT INTO msg VALUES(119,'%s has accepted your duel request');
INSERT INTO msg VALUES(120,'%s has rejected your duel request');
INSERT INTO msg VALUES(121,'You have accepted %s''s duel request');
INSERT INTO msg VALUES(122,'You have rejected %s''s duel request');
INSERT INTO msg VALUES(123,'%s wants to challenge you in a %s duel. Do you accept?');
INSERT INTO msg VALUES(124,'%s has won the duel against %s');
INSERT INTO msg VALUES(125,'You have won the duel against %s');
INSERT INTO msg VALUES(126,'You have lost the duel against %s');
INSERT INTO msg VALUES(127,'You are already dueling with %s');
INSERT INTO msg VALUES(128,'%s is already dueling');
INSERT INTO msg VALUES(129,'%s has won the duel against %s');
INSERT INTO msg VALUES(130,'The duel has ended with a draw');
INSERT INTO msg VALUES(131,'The duel between %s and %s has ended with a draw');
INSERT INTO msg VALUES(132,'You''re already dueling');
INSERT INTO msg VALUES(133,'You need to be level 10 to duel');
INSERT INTO msg VALUES(134,'%s needs to be at least level 10 to duel');
CREATE TABLE plant (plant_id INTEGER PRIMARY KEY, name TEXT, model_dir TEXT, model_file TEXT, animation TEXT, scale NUMERIC);
INSERT INTO plant VALUES(1,'acacia_l','trees/with_leaves','acaciatree_billboard','',16);
INSERT INTO plant VALUES(2,'acacia_nl','trees/without_leaves','acaciatree_billboard_noleaves','',16);
INSERT INTO plant VALUES(3,'bigtree','bigTree','bigTree','',7);
INSERT INTO plant VALUES(4,'boabab_bl','trees/brownleaves','baobabtree','',16);
INSERT INTO plant VALUES(5,'boabab_l','trees/with_leaves','baobabtree','',16);
INSERT INTO plant VALUES(6,'decayingmaterial','decayingmaterial','decayingmaterial','',16);
INSERT INTO plant VALUES(7,'drygrass','trees/grass','drygrass','',3);
INSERT INTO plant VALUES(8,'greengrass','trees/grass','greenGrass','',3);
COMMIT;
